import { Knex } from 'knex';
import { ETableNames } from '../ETableNames';

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    '* as count'
  );
  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = cidadesDoMatoGrossoDoSul.map((nomeDaCidade) => ({
    nome: nomeDaCidade,
  }));
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidadesDoMatoGrossoDoSul = [
  'Água Clara',
  'Alcinópolis',
  'Amambaí',
  'Anastácio',
  'Anaurilândia',
  'Angélica',
  'Antônio João',
  'Aparecida do Taboado',
  'Aquidauana',
  'Aral Moreira',
  'Bandeirantes',
  'Bataguassu',
  'Bataiporã',
  'Bela Vista',
  'Bodoquena',
  'Bonito',
  'Brasilândia',
  'Caarapó',
  'Camapuã',
  'Campo Grande',
  'Caracol',
  'Cassilândia',
  'Chapadão do Sul',
  'Corguinho',
  'Coronel Sapucaia',
  'Corumbá',
  'Costa Rica',
  'Coxim',
  'Deodápolis',
  'Dois Irmãos do Buriti',
  'Douradina',
  'Dourados',
  'Eldorado',
  'Fátima do Sul',
  'Glória de Dourados',
  'Guia Lopes da Laguna',
  'Iguatemi',
  'Inocência',
  'Itaporã',
  'Itaquiraí',
  'Ivinhema',
  'Japorã',
  'Jaraguari',
  'Jardim',
  'Jateí',
  'Juti',
  'Ladário',
  'Laguna Carapã',
  'Maracaju',
  'Miranda',
  'Mundo Novo',
  'Naviraí',
  'Nioaque',
  'Nova Alvorada do Sul',
  'Nova Andradina',
  'Novo Horizonte do Sul',
  'Paranaíba',
  'Paranhos',
  'Pedro Gomes',
  'Ponta Porã',
  'Porto Murtinho',
  'Ribas do Rio Pardo',
  'Rio Brilhante',
  'Rio Negro',
  'Rio Verde de Mato Grosso',
  'Rochedo',
  'Santa Rita do Pardo',
  'São Gabriel do Oeste',
  'Selvíria',
  'Sete Quedas',
  'Sidrolândia',
  'Sonora',
  'Tacuru',
  'Taquarussu',
  'Terenos',
  'Três Lagoas',
  'Vicentina',
];
